{
   'added_at':'2018-05-18T19:16:36Z',
   'track':{
      'album':{
         'album_type':'single',
         'artists':[
            {
               'external_urls':{
                  'spotify':'https://open.spotify.com/artist/64KEffDW9EtZ1y2vBYgq8T'
               },
               'href':'https://api.spotify.com/v1/artists/64KEffDW9EtZ1y2vBYgq8T',
               'id':'64KEffDW9EtZ1y2vBYgq8T',
               'name':'Marshmello',
               'type':'artist',
               'uri':'spotify:artist:64KEffDW9EtZ1y2vBYgq8T'
            },
            {
               'external_urls':{
                  'spotify':'https://open.spotify.com/artist/5gCRApTajqwbnHHPbr2Fpi'
               },
               'href':'https://api.spotify.com/v1/artists/5gCRApTajqwbnHHPbr2Fpi',
               'id':'5gCRApTajqwbnHHPbr2Fpi',
               'name':'Juicy J',
               'type':'artist',
               'uri':'spotify:artist:5gCRApTajqwbnHHPbr2Fpi'
            },
            {
               'external_urls':{
                  'spotify':'https://open.spotify.com/artist/4IWBUUAFIplrNtaOHcJPRM'
               },
               'href':'https://api.spotify.com/v1/artists/4IWBUUAFIplrNtaOHcJPRM',
               'id':'4IWBUUAFIplrNtaOHcJPRM',
               'name':'James Arthur',
               'type':'artist',
               'uri':'spotify:artist:4IWBUUAFIplrNtaOHcJPRM'
            }
         ],
         'available_markets':[
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
         ],
         'external_urls':{
            'spotify':'https://open.spotify.com/album/6TvqOieExu0IJb9Q1gOoCz'
         },
         'href':'https://api.spotify.com/v1/albums/6TvqOieExu0IJb9Q1gOoCz',
         'id':'6TvqOieExu0IJb9Q1gOoCz',
         'images':[
            {
               'height':640,
               'url':'https://i.scdn.co/image/b3556956b8e4881c85228ada91aa953e5c0458ef',
               'width':640
            },
            {
               'height':300,
               'url':'https://i.scdn.co/image/d76072f5ca739466bd27f42f3356fa1a38c6a92d',
               'width':300
            },
            {
               'height':64,
               'url':'https://i.scdn.co/image/bfd092dfa503566d9c9a3042f213fe02bed8a5cc',
               'width':64
            }
         ],
         'name':'You Can Cry',
         'release_date':'2018-05-04',
         'release_date_precision':'day',
         'type':'album',
         'uri':'spotify:album:6TvqOieExu0IJb9Q1gOoCz'
      },
      'artists':[
         {
            'external_urls':{
               'spotify':'https://open.spotify.com/artist/64KEffDW9EtZ1y2vBYgq8T'
            },
            'href':'https://api.spotify.com/v1/artists/64KEffDW9EtZ1y2vBYgq8T',
            'id':'64KEffDW9EtZ1y2vBYgq8T',
            'name':'Marshmello',
            'type':'artist',
            'uri':'spotify:artist:64KEffDW9EtZ1y2vBYgq8T'
         },
         {
            'external_urls':{
               'spotify':'https://open.spotify.com/artist/5gCRApTajqwbnHHPbr2Fpi'
            },
            'href':'https://api.spotify.com/v1/artists/5gCRApTajqwbnHHPbr2Fpi',
            'id':'5gCRApTajqwbnHHPbr2Fpi',
            'name':'Juicy J',
            'type':'artist',
            'uri':'spotify:artist:5gCRApTajqwbnHHPbr2Fpi'
         },
         {
            'external_urls':{
               'spotify':'https://open.spotify.com/artist/4IWBUUAFIplrNtaOHcJPRM'
            },
            'href':'https://api.spotify.com/v1/artists/4IWBUUAFIplrNtaOHcJPRM',
            'id':'4IWBUUAFIplrNtaOHcJPRM',
            'name':'James Arthur',
            'type':'artist',
            'uri':'spotify:artist:4IWBUUAFIplrNtaOHcJPRM'
         }
      ],
      'available_markets':[
         'AD',
         'AR',
         'AT',
         'AU',
         'BE',
         'BG',
         'BO',
         'BR',
         'CA',
         'CH',
         'CL',
         'CO',
         'CR',
         'CY',
         'CZ',
         'DE',
         'DK',
         'DO',
         'EC',
         'EE',
         'ES',
         'FI',
         'FR',
         'GB',
         'GR',
         'GT',
         'HK',
         'HN',
         'HU',
         'ID',
         'IE',
         'IL',
         'IS',
         'IT',
         'JP',
         'LI',
         'LT',
         'LU',
         'LV',
         'MC',
         'MT',
         'MX',
         'MY',
         'NI',
         'NL',
         'NO',
         'NZ',
         'PA',
         'PE',
         'PH',
         'PL',
         'PT',
         'PY',
         'RO',
         'SE',
         'SG',
         'SK',
         'SV',
         'TH',
         'TR',
         'TW',
         'US',
         'UY',
         'VN',
         'ZA'
      ],
      'disc_number':1,
      'duration_ms':194533,
      'explicit':False,
      'external_ids':{
         'isrc':'USQX91800946'
      },
      'external_urls':{
         'spotify':'https://open.spotify.com/track/3ZbJMlEL4Kcme0ONRO7Slx'
      },
      'href':'https://api.spotify.com/v1/tracks/3ZbJMlEL4Kcme0ONRO7Slx',
      'id':'3ZbJMlEL4Kcme0ONRO7Slx',
      'name':'You Can Cry',
      'popularity':81,
      'preview_url':'https://p.scdn.co/mp3-preview/6c31f3dee18a1e7c452ce9b6948a6e04aa7629d6?cid=aefd4e45060d4f9ba5bea0f6e6d36359',
      'track_number':1,
      'type':'track',
      'uri':'spotify:track:3ZbJMlEL4Kcme0ONRO7Slx'
   }
}
