# Generated by Django 2.0.5 on 2018-06-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('runtime', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='spotifyvis.Track')),
                ('danceability', models.DecimalField(decimal_places=2, max_digits=2)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=2)),
                ('loudness', models.DecimalField(decimal_places=2, max_digits=2)),
                ('speechiness', models.DecimalField(decimal_places=2, max_digits=2)),
                ('acousticness', models.DecimalField(decimal_places=2, max_digits=2)),
                ('instrumentalness', models.DecimalField(decimal_places=2, max_digits=2)),
                ('valence', models.DecimalField(decimal_places=2, max_digits=2)),
                ('tempo', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name': 'AudioFeatures',
                'verbose_name_plural': 'AudioFeatures',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(to='spotifyvis.Artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='users',
            field=models.ManyToManyField(to='spotifyvis.User'),
        ),
    ]
