# Generated by Django 2.0.5 on 2018-06-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyvis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofeatures',
            name='acousticness',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='danceability',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='energy',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='instrumentalness',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='loudness',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='speechiness',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='tempo',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='valence',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
