# Generated by Django 2.0.5 on 2018-06-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyvis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artists',
        ),
    ]
