# Generated by Django 2.0.5 on 2018-06-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyvis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=30),
        ),
    ]
