# Generated by Django 2.0.5 on 2018-06-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyvis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
