# Generated by Django 2.0.5 on 2018-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyvis', '0002_auto_20180605_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
